[package]
name = "solana-vrf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.16"
borsh = "0.10"
borsh-derive = "0.10"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
thiserror = "1.0"
